"""Chunked data stream for long runs that do not fit on disk.

The CPU generates chunk k+1 while the GPU trains on chunk k; a chunk is deleted once every
consumer has finished it, so the disk holds `ahead` chunks instead of the whole run. Each chunk
is a set of ordinary pools (one per prior) with seed = seed_base + chunk index, so any chunk can
be regenerated byte-identically. Training reads chunk k for steps [k*S, (k+1)*S) with epoch
sampling (every shard once) and stops there with a checkpoint (`lightpfn.train --stop-at`); the
next segment resumes from that checkpoint on chunk k+1. The producer waits when it is `ahead`
chunks in front of the slowest consumer or the disk is short; a consumer waits when its chunk
is not ready. Every command can be rerun after a crash and continues where it stopped.

Layout: STREAM/spec.json, STREAM/c000007/<label>/shard_*.pt, STREAM/c000007/READY,
STREAM/consumers/<run>.json, STREAM/GEN_DONE or STREAM/GEN_FAILED.

    python -m lightpfn.prior.stream init STREAM --chunk-steps 8000 --chunks 20 --consumers F1 F2 \\
        --prior v3=graph:3:0.55:0.9:3000000 --prior rule=rule:1:0.78:0.1:5000000
    python -m lightpfn.prior.stream gen STREAM --n-jobs 92 --ahead 4
    python -m lightpfn.prior.stream train STREAM --run F1 --gpu 0 --eval-script eval.sh -- \\
        --warmup 2000 --max-cells 1000000 --eval-every 8000 --workers 4 --seed 0 --config '{"row_mode":"summary"}'
    python -m lightpfn.prior.stream status STREAM
"""
import argparse
import contextlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHARD_TASKS = 256  # s1b: 32 groups of 8 tasks per shard
TASKS_PER_STEP = 32  # lightpfn.train: 4 groups of 8 tasks
RESERVED_SEEDS = {0, 1, 20261010, 20261011, 0xD1DE0001}  # existing pools and the D1 dev set
OWNED_TRAIN_FLAGS = {"--run", "--pools", "--steps", "--stop-at", "--sampling"}
CHUNK_RE = re.compile(r"c(\d{6})")


def log(msg):
    print(f"{time.strftime('%F %T')} {msg}", flush=True)


def atomic_json(path, obj):
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(obj, indent=2))
    tmp.replace(path)


@contextlib.contextmanager
def stream_lock(stream):
    import fcntl
    with open(stream / ".lock", "a") as f:
        fcntl.flock(f, fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(f, fcntl.LOCK_UN)


def parse_prior(text):
    """label=prior:version:p_binary:weight:seed_base"""
    m = re.fullmatch(r"([A-Za-z0-9_]+)=(graph|rule|tree):(\d+):([0-9.]+):([0-9.]+):(\d+)", text)
    if m is None:
        raise ValueError(f"prior must be label=prior:version:p_binary:weight:seed_base, got {text!r}")
    label, prior, version, p_binary, weight, seed_base = m.groups()
    return dict(label=label, prior=prior, version=int(version), p_binary=float(p_binary),
                weight=float(weight), seed_base=int(seed_base))


def make_spec(chunk_steps, chunks, consumers, priors, margin=0.05, tasks_per_step=TASKS_PER_STEP, passes=1):
    """tasks_per_step: tasks of one optimizer step over every rank (32 x ranks with 4 groups of 8).
    passes: how many times training reads each chunk (epoch sampling; new column order and
    missingness each time): the chunk holds 1/passes of the tasks drawn from it."""
    if (chunk_steps < 1 or chunks < 1 or not consumers or len(set(consumers)) != len(consumers) or not priors
            or tasks_per_step < 1 or passes < 1):
        raise ValueError("invalid chunk steps/chunks/consumers/priors/tasks per step/passes")
    if any(not re.fullmatch(r"[A-Za-z0-9_.-]+", c) for c in consumers):
        raise ValueError("consumer names must be plain run names")
    if len({p["label"] for p in priors}) != len(priors) or not 0 <= margin <= 1:
        raise ValueError("duplicate prior labels or invalid margin")
    total = sum(p["weight"] for p in priors)
    if not total > 0 or any(not p["weight"] > 0 or not 0 <= p["p_binary"] <= 1 for p in priors):
        raise ValueError("weights must be positive and p_binary in [0, 1]")
    seeds = [p["seed_base"] + k for p in priors for k in range(chunks)]
    if len(set(seeds)) != len(seeds) or max(seeds) >= 2**32 or RESERVED_SEEDS & set(seeds):
        raise ValueError("chunk seeds overlap each other, existing pools or the D1 dev seed")
    out = []
    for p in priors:
        w = p["weight"] / total
        # Margin over the expected draws: the per-worker slices of an epoch-sampled chunk then
        # rarely run out, which would reread a few shards.
        tasks = math.ceil(w * chunk_steps * tasks_per_step * (1 + margin) / passes / SHARD_TASKS) * SHARD_TASKS
        out.append(dict(p, weight=w, tasks=tasks))
    return dict(chunk_steps=chunk_steps, chunks=chunks, total_steps=chunk_steps * chunks,
                tasks_per_step=tasks_per_step, passes=passes, consumers=list(consumers), priors=out,
                margin=margin, preset="s1b", geometry="ratio", max_features=100)


def load_spec(stream):
    return json.loads((stream / "spec.json").read_text())


def chunk_dir(stream, k):
    return stream / f"c{k:06d}"


def consumer_state(stream, run):
    path = stream / "consumers" / f"{run}.json"
    if path.exists():
        return json.loads(path.read_text())
    return dict(done=0, state="running", waited_s=0.0)


def write_consumer(stream, run, state):
    (stream / "consumers").mkdir(exist_ok=True)
    atomic_json(stream / "consumers" / f"{run}.json", dict(state, updated=time.strftime("%F %T")))


def floor_chunk(stream, spec):
    """Chunks below this index are finished by every consumer still reading (not done, not failed)."""
    states = [consumer_state(stream, r) for r in spec["consumers"]]
    held = [s["done"] for s in states if s["state"] not in ("failed", "done")]
    return min(held) if held else spec["chunks"]


def cleanup(stream, spec):
    with stream_lock(stream):
        floor = floor_chunk(stream, spec)
        for d in sorted(stream.iterdir()):
            m = CHUNK_RE.fullmatch(d.name)
            if d.is_dir() and m and int(m[1]) < floor:
                shutil.rmtree(d)
                log(f"deleted {d.name} (finished by every consumer)")
    return floor


def pool_complete(out, tasks):
    """A generator run that stops on disk space exits 0 with a partial pool: count the shards.
    More shards than needed (a pool carried over from a larger chunk, same seed) is complete too."""
    if not (out / "meta.json").exists():
        return False
    return len(list(out.glob("shard_*.pt"))) >= math.ceil(tasks / SHARD_TASKS)


def carried_over(out, item, seed, spec):
    """A complete pool with this chunk's seed and settings is already in place (moved in from another
    stream). It is not passed to generate.py: that refuses an n_tasks below the shards it finds."""
    if not pool_complete(out, item["tasks"]):
        return False
    meta = json.loads((out / "meta.json").read_text())
    want = dict(seed=seed, prior=item["prior"], prior_version=item["version"], p_binary=item["p_binary"],
                preset=spec["preset"], geometry=spec["geometry"], max_features=spec["max_features"])
    return all(meta.get(key) == value for key, value in want.items())


def gen_command(spec, item, out, seed, n_jobs, min_free_gb, lookahead=8):
    # --lookahead only schedules (shards byte-identical): more shards in flight keep many workers busy
    return [sys.executable, "-m", "lightpfn.prior.generate", "--preset", spec["preset"], "--prior", item["prior"],
            "--prior-version", str(item["version"]), "--geometry", spec["geometry"],
            "--p-binary", str(item["p_binary"]), "--max-features", str(spec["max_features"]),
            "--seed", str(seed), "--n-tasks", str(item["tasks"]), "--n-jobs", str(n_jobs),
            "--min-free-gb", str(min_free_gb), "--lookahead", str(lookahead), "--out", str(out)]


def _nice():
    os.nice(10)


def free_gb(path):
    return shutil.disk_usage(path).free / 1e9


def generate(stream, n_jobs=92, ahead=4, min_free_gb=30.0, lookahead=8, gb_per_ktask=0.09, poll=60, retries=3,
             run=subprocess.run, sleep=time.sleep):
    spec = load_spec(stream)
    chunk_gb = gb_per_ktask * sum(p["tasks"] for p in spec["priors"]) / 1000
    env = dict(os.environ, CUDA_VISIBLE_DEVICES="", OMP_NUM_THREADS="1", OPENBLAS_NUM_THREADS="1",
               MKL_NUM_THREADS="1", NUMEXPR_NUM_THREADS="1")
    (stream / "GEN_FAILED").unlink(missing_ok=True)  # a rerun is a retry
    for k in range(spec["chunks"]):
        cdir = chunk_dir(stream, k)
        waited, last_note = 0.0, -1
        while True:
            floor = cleanup(stream, spec)
            if floor >= spec["chunks"]:
                log("every consumer is done or failed: stopping")
                return 0
            if k < floor or (cdir / "READY").exists():
                break  # consumed by everyone (rerun after a crash) or already generated
            free = free_gb(stream)
            if k - floor < ahead and free >= chunk_gb + min_free_gb:
                break
            if waited // 600 != last_note:
                last_note = waited // 600
                log(f"chunk {k} waits: slowest consumer at chunk {floor}, ahead {ahead}, free {free:.0f} GB "
                    f"(needs {chunk_gb + min_free_gb:.0f})")
            sleep(poll)
            waited += poll
        if k < floor or (cdir / "READY").exists():
            continue
        t0 = time.monotonic()
        for item in spec["priors"]:
            out = cdir / item["label"]
            if carried_over(out, item, item["seed_base"] + k, spec):
                log(f"chunk {k} {item['label']}: complete pool already in place, not regenerated")
                continue
            cmd = gen_command(spec, item, out, item["seed_base"] + k, n_jobs, min(min_free_gb, 20.0), lookahead)
            for attempt in range(retries + 1):
                out.parent.mkdir(parents=True, exist_ok=True)
                with open(stream / f"gen_{item['label']}.log", "a") as f:
                    rc = run(cmd, cwd=ROOT, env=env, stdout=f, stderr=subprocess.STDOUT, preexec_fn=_nice).returncode
                if rc == 0 and pool_complete(out, item["tasks"]):
                    break
                log(f"chunk {k} {item['label']}: exit {rc}, incomplete; retry {attempt + 1}/{retries} in {poll * 5}s")
                sleep(poll * 5)
            else:
                (stream / "GEN_FAILED").write_text(f"chunk {k} {item['label']}\n")
                log(f"chunk {k} {item['label']} failed {retries + 1} times: GEN_FAILED")
                return 1
        atomic_json(cdir / "READY", dict(chunk=k, seconds=time.monotonic() - t0,
                                         tasks={p["label"]: p["tasks"] for p in spec["priors"]}))
        log(f"chunk {k} ready in {time.monotonic() - t0:.0f}s")
    (stream / "GEN_DONE").write_text("done\n")
    log("all chunks generated")
    return 0


def train_command(stream, spec, run_name, k, train_args, chunks=None, nproc=1):
    total = (chunks or spec["chunks"]) * spec["chunk_steps"]
    pools = [f"{chunk_dir(stream, k) / p['label']}:{p['weight']}" for p in spec["priors"]]
    stop = min((k + 1) * spec["chunk_steps"], total)
    launcher = [sys.executable, "-m", "lightpfn.train"] if nproc == 1 else [
        sys.executable, "-m", "torch.distributed.run", "--standalone", f"--nproc_per_node={nproc}", "-m", "lightpfn.train"]
    return [*launcher, "--run", run_name, "--pools", *pools,
            "--steps", str(total), "--stop-at", str(stop), "--sampling", "epoch", *train_args]


def consume(stream, run_name, gpu, train_args, eval_script=None, chunks=None, nproc=1, poll=60, retries=2,
            run=subprocess.run, popen=subprocess.Popen, sleep=time.sleep):
    """Train run_name on the first `chunks` chunks (default all): its schedule ends at chunks x chunk_steps.
    gpu: one index, or a comma list with nproc > 1 (data parallel over those GPUs through torchrun)."""
    spec = load_spec(stream)
    if run_name not in spec["consumers"]:
        raise ValueError(f"{run_name} is not a consumer of {stream}")
    if OWNED_TRAIN_FLAGS & {a.split("=")[0] for a in train_args}:
        raise ValueError(f"the stream sets {sorted(OWNED_TRAIN_FLAGS)} itself")
    if nproc < 1 or len(str(gpu).split(",")) != nproc:
        raise ValueError("give one GPU per process (--gpu 0,1 with --nproc 2)")
    if spec.get("tasks_per_step", TASKS_PER_STEP) != TASKS_PER_STEP * nproc:
        log(f"warning: spec has {spec.get('tasks_per_step')} tasks per step, {nproc} rank(s) of 4 groups draw "
            f"{TASKS_PER_STEP * nproc}: chunk sizes will not match the draws")
    chunks = chunks or spec["chunks"]
    if not 1 <= chunks <= spec["chunks"]:
        raise ValueError(f"chunks must be in 1..{spec['chunks']}")
    state = consumer_state(stream, run_name)
    if state.setdefault("chunks", chunks) != chunks:
        raise ValueError(f"{run_name} started with {state['chunks']} chunks: its LR schedule depends on it")
    if state["state"] == "failed":
        log(f"{run_name} marked failed earlier: reset {stream}/consumers/{run_name}.json to retry")
        return 1
    state["state"] = "running"
    write_consumer(stream, run_name, state)
    env = dict(os.environ, CUDA_VISIBLE_DEVICES=str(gpu), PYTORCH_ALLOC_CONF="expandable_segments:True")
    run_dir = ROOT / "runs" / "train" / run_name
    total = chunks * spec["chunk_steps"]
    for k in range(state["done"], chunks):
        ready, waited = chunk_dir(stream, k) / "READY", 0.0
        while not ready.exists():
            if (stream / "GEN_FAILED").exists():
                # Not "failed": this run keeps its chunks and continues when both are rerun.
                log(f"{run_name}: generator failed, stopping at chunk {k}")
                write_consumer(stream, run_name, dict(state, state="stopped"))
                return 1
            if waited % 600 == 0:
                log(f"{run_name}: waiting for chunk {k}")
            sleep(poll)
            waited += poll
        state["waited_s"] = state.get("waited_s", 0.0) + waited
        cmd = train_command(stream, spec, run_name, k, train_args, chunks, nproc)
        stop = int(cmd[cmd.index("--stop-at") + 1])
        for attempt in range(retries + 1):
            log(f"{run_name}: chunk {k}, steps to {stop} (attempt {attempt + 1})")
            with open(ROOT / "runs" / f"train_{run_name}.log", "a") as f:
                rc = run(cmd, cwd=ROOT, env=env, stdout=f, stderr=subprocess.STDOUT).returncode
            if rc == 0:
                break
            sleep(poll)  # resumes from ckpt.pt (saved every --save-every steps)
        else:
            log(f"{run_name}: chunk {k} failed {retries + 1} times: consumer failed")
            write_consumer(stream, run_name, dict(state, state="failed"))
            cleanup(stream, spec)
            return 1
        state["done"] = k + 1
        write_consumer(stream, run_name, state)
        cleanup(stream, spec)
        ckpt = run_dir / f"ema_step{stop:06d}.pt"
        if eval_script and ckpt.exists():
            name = run_name if stop == total else f"{run_name}_s{stop}"
            with open(ROOT / "runs" / "eval_remote.log", "a") as f:
                popen(["flock", str(ROOT / "runs" / ".eval.lock"), str(eval_script), name, str(ckpt)],
                      cwd=ROOT, stdout=f, stderr=subprocess.STDOUT, start_new_session=True)
    write_consumer(stream, run_name, dict(state, state="done"))
    cleanup(stream, spec)  # a finished consumer no longer holds chunks
    log(f"{run_name}: all {chunks} chunks done")
    return 0


def status(stream):
    spec = load_spec(stream)
    chunks = sorted(d.name for d in stream.iterdir() if d.is_dir() and CHUNK_RE.fullmatch(d.name))
    ready = [c for c in chunks if (stream / c / "READY").exists()]
    print(f"{stream}: {spec['chunks']} chunks x {spec['chunk_steps']} steps; on disk {chunks}; ready {ready}; "
          f"free {free_gb(stream):.0f} GB; "
          f"{'GEN_DONE' if (stream / 'GEN_DONE').exists() else 'GEN_FAILED' if (stream / 'GEN_FAILED').exists() else 'generating'}")
    for r in spec["consumers"]:
        s = consumer_state(stream, r)
        print(f"  {r}: {s['done']}/{s.get('chunks', spec['chunks'])} chunks, {s['state']}, "
              f"waited {s.get('waited_s', 0) / 60:.0f} min")


def main(argv=None):
    # Everything after "--" goes to lightpfn.train untouched. Split it off before argparse: a
    # REMAINDER positional after `stream` would also swallow --run/--gpu.
    argv = list(sys.argv[1:] if argv is None else argv)
    train_args = argv[argv.index("--") + 1:] if "--" in argv else []
    argv = argv[:argv.index("--")] if "--" in argv else argv
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="action", required=True)
    i = sub.add_parser("init")
    i.add_argument("stream", type=Path)
    i.add_argument("--chunk-steps", type=int, default=8000)
    i.add_argument("--chunks", type=int, required=True)
    i.add_argument("--consumers", nargs="+", required=True)
    i.add_argument("--prior", action="append", required=True, type=parse_prior)
    i.add_argument("--margin", type=float, default=0.05)
    i.add_argument("--tasks-per-step", type=int, default=TASKS_PER_STEP, help="over every rank: 32 x ranks")
    i.add_argument("--passes", type=int, default=1, help="times training reads each chunk")
    g = sub.add_parser("gen")
    g.add_argument("stream", type=Path)
    g.add_argument("--n-jobs", type=int, default=92)
    g.add_argument("--ahead", type=int, default=4)
    g.add_argument("--min-free-gb", type=float, default=30.0)
    g.add_argument("--lookahead", type=int, default=8, help="shards in flight per generator (scheduling only)")
    t = sub.add_parser("train")
    t.add_argument("stream", type=Path)
    t.add_argument("--run", required=True)
    t.add_argument("--gpu", required=True)
    t.add_argument("--eval-script", type=Path)
    t.add_argument("--chunks", type=int, help="train on the first N chunks only (default: all)")
    t.add_argument("--nproc", type=int, default=1, help="data-parallel ranks (torchrun), one per --gpu entry")
    s = sub.add_parser("status")
    s.add_argument("stream", type=Path)
    args = ap.parse_args(argv)
    if train_args and args.action != "train":
        ap.error("arguments after -- are only for train")
    stream = args.stream.resolve()
    if args.action == "init":
        spec = make_spec(args.chunk_steps, args.chunks, args.consumers, args.prior, args.margin, args.tasks_per_step,
                         args.passes)
        stream.mkdir(parents=True, exist_ok=True)
        if (stream / "spec.json").exists() and load_spec(stream) != spec:
            raise SystemExit(f"{stream}/spec.json exists with other settings")
        atomic_json(stream / "spec.json", spec)
        print(json.dumps(spec, indent=2))
        return 0
    if args.action == "gen":
        return generate(stream, args.n_jobs, args.ahead, args.min_free_gb, args.lookahead)
    if args.action == "train":
        return consume(stream, args.run, args.gpu, train_args, args.eval_script, args.chunks, args.nproc)
    status(stream)
    return 0


if __name__ == "__main__":
    sys.exit(main())
